
package https.siat_impuestos_gob_bo.facturaelectronicaestandar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import https.siat_impuestos_gob.ObjectFactory;
import https.siat_impuestos_gob.Respuesta;
import https.siat_impuestos_gob.SolicitudAnulacion;
import https.siat_impuestos_gob.SolicitudRecepcion;
import https.siat_impuestos_gob.SolicitudValidacionAnulacion;
import https.siat_impuestos_gob.SolicitudValidacionRecepcion;
import https.siat_impuestos_gob.SolicitudValidacionRecepcionPorCuf;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServicioFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServicioFacturaElectronicaEstandar {


    /**
     * 
     * @param solicitudServicioValidacionRecepcionPorCuf
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionPorCufFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionPorCufFacturaElectronicaEstandar")
    @ResponseWrapper(localName = "validacionRecepcionPorCufFacturaElectronicaEstandarResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionPorCufFacturaElectronicaEstandarResponse")
    public Respuesta validacionRecepcionPorCufFacturaElectronicaEstandar(
        @WebParam(name = "SolicitudServicioValidacionRecepcionPorCuf", targetNamespace = "")
        SolicitudValidacionRecepcionPorCuf solicitudServicioValidacionRecepcionPorCuf);

    /**
     * 
     * @param solicitudServicioRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionPaqueteFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionPaqueteFacturaElectronicaEstandar")
    @ResponseWrapper(localName = "recepcionPaqueteFacturaElectronicaEstandarResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionPaqueteFacturaElectronicaEstandarResponse")
    public Respuesta recepcionPaqueteFacturaElectronicaEstandar(
        @WebParam(name = "SolicitudServicioRecepcion", targetNamespace = "")
        SolicitudRecepcion solicitudServicioRecepcion);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.VerificarComunicacionResponse")
    public int verificarComunicacion();

    /**
     * 
     * @param solicitudServicioValidacionAnulacion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionAnulacionFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionAnulacionFacturaElectronicaEstandar")
    @ResponseWrapper(localName = "validacionAnulacionFacturaElectronicaEstandarResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionAnulacionFacturaElectronicaEstandarResponse")
    public Respuesta validacionAnulacionFacturaElectronicaEstandar(
        @WebParam(name = "SolicitudServicioValidacionAnulacion", targetNamespace = "")
        SolicitudValidacionAnulacion solicitudServicioValidacionAnulacion);

    /**
     * 
     * @param solicitudServicioValidacionRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionFacturaElectronicaEstandar")
    @ResponseWrapper(localName = "validacionRecepcionFacturaElectronicaEstandarResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionFacturaElectronicaEstandarResponse")
    public Respuesta validacionRecepcionFacturaElectronicaEstandar(
        @WebParam(name = "SolicitudServicioValidacionRecepcion", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcion);

    /**
     * 
     * @param solicitudServicioRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionFacturaElectronicaEstandar")
    @ResponseWrapper(localName = "recepcionFacturaElectronicaEstandarResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionFacturaElectronicaEstandarResponse")
    public Respuesta recepcionFacturaElectronicaEstandar(
        @WebParam(name = "SolicitudServicioRecepcion", targetNamespace = "")
        SolicitudRecepcion solicitudServicioRecepcion);

    /**
     * 
     * @param solicitudServicioRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionMasivaFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionMasivaFacturaElectronicaEstandar")
    @ResponseWrapper(localName = "recepcionMasivaFacturaElectronicaEstandarResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionMasivaFacturaElectronicaEstandarResponse")
    public Respuesta recepcionMasivaFacturaElectronicaEstandar(
        @WebParam(name = "SolicitudServicioRecepcion", targetNamespace = "")
        SolicitudRecepcion solicitudServicioRecepcion);

    /**
     * 
     * @param solicitudServicioValidacionRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionMasivaFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionMasivaFacturaElectronicaEstandar")
    @ResponseWrapper(localName = "validacionRecepcionMasivaFacturaElectronicaEstandarResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionMasivaFacturaElectronicaEstandarResponse")
    public Respuesta validacionRecepcionMasivaFacturaElectronicaEstandar(
        @WebParam(name = "SolicitudServicioValidacionRecepcion", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcion);

    /**
     * 
     * @param solicitudServicioAnulacion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "anulacionFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.AnulacionFacturaElectronicaEstandar")
    @ResponseWrapper(localName = "anulacionFacturaElectronicaEstandarResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.AnulacionFacturaElectronicaEstandarResponse")
    public Respuesta anulacionFacturaElectronicaEstandar(
        @WebParam(name = "SolicitudServicioAnulacion", targetNamespace = "")
        SolicitudAnulacion solicitudServicioAnulacion);

    /**
     * 
     * @param solicitudServicioValidacionRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionPaqueteFacturaElectronicaEstandar", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionPaqueteFacturaElectronicaEstandar")
    @ResponseWrapper(localName = "validacionRecepcionPaqueteFacturaElectronicaEstandarResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionPaqueteFacturaElectronicaEstandarResponse")
    public Respuesta validacionRecepcionPaqueteFacturaElectronicaEstandar(
        @WebParam(name = "SolicitudServicioValidacionRecepcion", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcion);

}
