
package https.siat_impuestos_gob_bo.facturaelectronicaprevalorada;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import https.siat_impuestos_gob.ObjectFactory;
import https.siat_impuestos_gob.Respuesta;
import https.siat_impuestos_gob.SolicitudAnulacion;
import https.siat_impuestos_gob.SolicitudRecepcion;
import https.siat_impuestos_gob.SolicitudValidacionAnulacion;
import https.siat_impuestos_gob.SolicitudValidacionRecepcion;
import https.siat_impuestos_gob.SolicitudValidacionRecepcionPorCufp;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServicioFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServicioFacturaElectronicaPrevalorada {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarComunicacion", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.VerificarComunicacion")
    @ResponseWrapper(localName = "verificarComunicacionResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.VerificarComunicacionResponse")
    public int verificarComunicacion();

    /**
     * 
     * @param solicitudServicioValidacionRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionMasivaFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionMasivaFacturaElectronicaPrevalorada")
    @ResponseWrapper(localName = "validacionRecepcionMasivaFacturaElectronicaPrevaloradaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionMasivaFacturaElectronicaPrevaloradaResponse")
    public Respuesta validacionRecepcionMasivaFacturaElectronicaPrevalorada(
        @WebParam(name = "SolicitudServicioValidacionRecepcion", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcion);

    /**
     * 
     * @param solicitudServicioRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionPaqueteFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionPaqueteFacturaElectronicaPrevalorada")
    @ResponseWrapper(localName = "recepcionPaqueteFacturaElectronicaPrevaloradaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionPaqueteFacturaElectronicaPrevaloradaResponse")
    public Respuesta recepcionPaqueteFacturaElectronicaPrevalorada(
        @WebParam(name = "SolicitudServicioRecepcion", targetNamespace = "")
        SolicitudRecepcion solicitudServicioRecepcion);

    /**
     * 
     * @param solicitudServicioRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionFacturaElectronicaPrevalorada")
    @ResponseWrapper(localName = "recepcionFacturaElectronicaPrevaloradaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionFacturaElectronicaPrevaloradaResponse")
    public Respuesta recepcionFacturaElectronicaPrevalorada(
        @WebParam(name = "SolicitudServicioRecepcion", targetNamespace = "")
        SolicitudRecepcion solicitudServicioRecepcion);

    /**
     * 
     * @param solicitudServicioRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "recepcionMasivaFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionMasivaFacturaElectronicaPrevalorada")
    @ResponseWrapper(localName = "recepcionMasivaFacturaElectronicaPrevaloradaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.RecepcionMasivaFacturaElectronicaPrevaloradaResponse")
    public Respuesta recepcionMasivaFacturaElectronicaPrevalorada(
        @WebParam(name = "SolicitudServicioRecepcion", targetNamespace = "")
        SolicitudRecepcion solicitudServicioRecepcion);

    /**
     * 
     * @param solicitudServicioValidacionRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionFacturaElectronicaPrevalorada")
    @ResponseWrapper(localName = "validacionRecepcionFacturaElectronicaPrevaloradaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionFacturaElectronicaPrevaloradaResponse")
    public Respuesta validacionRecepcionFacturaElectronicaPrevalorada(
        @WebParam(name = "SolicitudServicioValidacionRecepcion", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcion);

    /**
     * 
     * @param solicitudServicioValidacionAnulacion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionAnulacionFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionAnulacionFacturaElectronicaPrevalorada")
    @ResponseWrapper(localName = "validacionAnulacionFacturaElectronicaPrevaloradaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionAnulacionFacturaElectronicaPrevaloradaResponse")
    public Respuesta validacionAnulacionFacturaElectronicaPrevalorada(
        @WebParam(name = "SolicitudServicioValidacionAnulacion", targetNamespace = "")
        SolicitudValidacionAnulacion solicitudServicioValidacionAnulacion);

    /**
     * 
     * @param solicitudServicioValidacionRecepcion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionPaqueteFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionPaqueteFacturaElectronicaPrevalorada")
    @ResponseWrapper(localName = "validacionRecepcionPaqueteFacturaElectronicaPrevaloradaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionPaqueteFacturaElectronicaPrevaloradaResponse")
    public Respuesta validacionRecepcionPaqueteFacturaElectronicaPrevalorada(
        @WebParam(name = "SolicitudServicioValidacionRecepcion", targetNamespace = "")
        SolicitudValidacionRecepcion solicitudServicioValidacionRecepcion);

    /**
     * 
     * @param solicitudServicioValidacionRecepcionPorCuf
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "validacionRecepcionPorCufpFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionPorCufpFacturaElectronicaPrevalorada")
    @ResponseWrapper(localName = "validacionRecepcionPorCufpFacturaElectronicaPrevaloradaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.ValidacionRecepcionPorCufpFacturaElectronicaPrevaloradaResponse")
    public Respuesta validacionRecepcionPorCufpFacturaElectronicaPrevalorada(
        @WebParam(name = "SolicitudServicioValidacionRecepcionPorCuf", targetNamespace = "")
        SolicitudValidacionRecepcionPorCufp solicitudServicioValidacionRecepcionPorCuf);

    /**
     * 
     * @param solicitudServicioAnulacion
     * @return
     *     returns https.siat_impuestos_gob.Respuesta
     */
    @WebMethod
    @WebResult(name = "RespuestaServicioFacturacion", targetNamespace = "")
    @RequestWrapper(localName = "anulacionFacturaElectronicaPrevalorada", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.AnulacionFacturaElectronicaPrevalorada")
    @ResponseWrapper(localName = "anulacionFacturaElectronicaPrevaloradaResponse", targetNamespace = "https://siat.impuestos.gob.bo/", className = "https.siat_impuestos_gob.AnulacionFacturaElectronicaPrevaloradaResponse")
    public Respuesta anulacionFacturaElectronicaPrevalorada(
        @WebParam(name = "SolicitudServicioAnulacion", targetNamespace = "")
        SolicitudAnulacion solicitudServicioAnulacion);

}
