
package https.siat_impuestos_gob_bo.facturaelectronicaprevalorada;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioFacturacionService", targetNamespace = "https://siat.impuestos.gob.bo/FacturaElectronicaPrevalorada", wsdlLocation = "META-INF/wsdl/ServicioFacturacionService.wsdl")
public class ServicioFacturacionService
    extends Service
{

    private final static URL SERVICIOFACTURACIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOFACTURACIONSERVICE_EXCEPTION;
    private final static QName SERVICIOFACTURACIONSERVICE_QNAME = new QName("https://siat.impuestos.gob.bo/FacturaElectronicaPrevalorada", "ServicioFacturacionService");

    static {
        SERVICIOFACTURACIONSERVICE_WSDL_LOCATION = https.siat_impuestos_gob_bo.facturaelectronicaprevalorada.ServicioFacturacionService.class.getClassLoader().getResource("META-INF/wsdl/ServicioFacturacionService.wsdl");
        WebServiceException e = null;
        if (SERVICIOFACTURACIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ServicioFacturacionService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SERVICIOFACTURACIONSERVICE_EXCEPTION = e;
    }

    public ServicioFacturacionService() {
        super(__getWsdlLocation(), SERVICIOFACTURACIONSERVICE_QNAME);
    }

    public ServicioFacturacionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOFACTURACIONSERVICE_QNAME, features);
    }

    public ServicioFacturacionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOFACTURACIONSERVICE_QNAME);
    }

    public ServicioFacturacionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOFACTURACIONSERVICE_QNAME, features);
    }

    public ServicioFacturacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioFacturacionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServicioFacturaElectronicaPrevalorada
     */
    @WebEndpoint(name = "ServicioFacturacionPort")
    public IServicioFacturaElectronicaPrevalorada getServicioFacturacionPort() {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/FacturaElectronicaPrevalorada", "ServicioFacturacionPort"), IServicioFacturaElectronicaPrevalorada.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServicioFacturaElectronicaPrevalorada
     */
    @WebEndpoint(name = "ServicioFacturacionPort")
    public IServicioFacturaElectronicaPrevalorada getServicioFacturacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://siat.impuestos.gob.bo/FacturaElectronicaPrevalorada", "ServicioFacturacionPort"), IServicioFacturaElectronicaPrevalorada.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOFACTURACIONSERVICE_EXCEPTION!= null) {
            throw SERVICIOFACTURACIONSERVICE_EXCEPTION;
        }
        return SERVICIOFACTURACIONSERVICE_WSDL_LOCATION;
    }

}
